# Generated by Django 4.1.7 on 2023-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0003_user_first_name_user_initial_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
