# Generated by Django 4.1.7 on 2023-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0005_alter_user_username_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="text",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="pin",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
