# Generated by Django 4.1.7 on 2023-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0008_account_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
