# Generated by Django 4.1.7 on 2023-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0010_account_created_at_pin_created_at_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="unique_id",
            field=models.BigIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pin",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
