# Generated by Django 4.2.5 on 2023-10-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0012_auto_20231006_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="unique_id",
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
