# Generated by Django 4.2.5 on 2023-11-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0015_account_profile_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="background_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
