# Generated by Django 5.0 on 2023-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinit_api", "0016_account_background_picture_url_account_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
