# Generated by Django 4.2.5 on 2024-02-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_api', '0024_alter_pinsave_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinInBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_saved_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='pinit_api.board')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinit_api.pin')),
            ],
            options={
                'unique_together': {('pin', 'board')},
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='saved_pins',
        ),
        migrations.DeleteModel(
            name='PinSave',
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='pinit_api.account'),
        ),
    ]
