# Generated by Django 5.0 on 2024-03-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_api', '0028_rename_cover_image_url_board_cover_picture_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pininboard',
            options={'verbose_name_plural': 'Pins in boards'},
        ),
    ]
