# Generated by Django 5.0 on 2024-03-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_api', '0029_alter_pininboard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cover_picture_url',
        ),
    ]
