# Generated by Django 5.0 on 2024-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinit_api', '0030_remove_board_cover_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('author', 'slug')},
        ),
    ]
