# Error codes
ERROR_CODE_INVALID_EMAIL = "invalid_email"
ERROR_CODE_INVALID_PASSWORD = "invalid_password"
ERROR_CODE_UNAUTHORIZED = "unauthorized"
ERROR_CODE_NOT_FOUND = "not_found"
ERROR_CODE_PIN_CREATION_FAILED = "pin_creation_failed"
ERROR_CODE_MISSING_PIN_IMAGE_FILE = "missing_pin_image_file"
ERROR_CODE_MISSING_USERNAME = "missing_username"
ERROR_CODE_WRONG_USERNAME = "wrong_username"
