name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker container
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Run migrations
        run: docker-compose -f docker-compose.test.yml exec -T web python manage.py migrate

      - name: Run tests with coverage
        run: |
          docker-compose -f docker-compose.test.yml exec -T web coverage run manage.py test
          docker-compose -f docker-compose.test.yml exec -T web coverage xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./app/coverage.xml

      - name: Shut down Docker container
        run: docker-compose -f docker-compose.test.yml down
