name: Continuous integration

on:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker container
        run: docker-compose -f docker-compose.ci.yml up -d
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Run migrations
        run: docker-compose -f docker-compose.ci.yml exec -T web python manage.py migrate

      - name: Run tests with coverage
        run: |
          docker-compose -f docker-compose.ci.yml exec -T web coverage run manage.py test
          docker-compose -f docker-compose.ci.yml exec -T web coverage xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./app/coverage.xml

      - name: Shut down Docker container
        run: docker-compose -f docker-compose.ci.yml down
