name: Delete Environment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  delete-environment:
    runs-on: ubuntu-latest
    environment:
      name: staging
    if: github.event.pull_request.merged == true || github.event.pull_request.head.ref != 'main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYMENT_AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Delete Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk terminate-environment --environment-name pinit-back-staging-${{ github.head_ref }} --no-hang

